* Weekly meeting
  SCHEDULED: <2020-11-01 Sun 09:00 +1w>
  :PROPERTIES:
  :ID:       50F4FB7A-752E-4C67-94D9-3FF43BF14183
  :END:
  [[https://meet.google.com/ody-sudr-hem][Google meetup]]

* Glenn's tasks
** Get familiar with Emacs
  [[info:Emacs][Emacs introduction]]

** TODO Short term goals ( week 2 )
    DEADLINE: <2020-15-11 Sun>

  - Learn basic github functions
    - [[https://git-scm.com/videos][Git videos]]
    - [[https://git-scm.com/book/en/v2][Git book]]
  - Make a pull request for Doug to see changes

*** TODO Short term goals ( week 1 )
    DEADLINE: <2020-11-01 Sun>
    :PROPERTIES:
    :ID:       22EB1B14-53EA-4176-B875-2ACE0EC880FE
    :END:

  - Create a buffer
  - Save a file

*** Learn Org Mode
  [[info:org][Org Mode manual]]
  
  
* Doug's tasks
** Manage weekly meeting
*** DONE Fix settings to share screen in Google Meetup.

*** DONE Create repository for this.
    DEADLINE: <2020-10-26 Mon>
    :PROPERTIES:
    :ID:       897CEA32-164A-43A8-8268-5BC30AE2347C
    :END:
  To keep in sync with our goals let's use an org mode file shared on GitHub.  This doc is found in
  [[https://github.com/gitonthescene/task-checkin][this repository]].

** Wikidata Senators
  This is a project to upload all historical senator data from [[https://bioguideretro.congress.gov/][US government sources]] to [[https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician/United_States_of_America][Wikidata]].
  The data has been collected and uploaded to [[https://github.com/gitonthescene/wikidata/tree/master/every_politician/United_States_of_America/Senate][GitHub]].  Some processing was done using [[https://openrefine.org/documentation.html][OpenRefine]] and
  then subsequently uploaded to Wikidata with a basic schema.  (E.g. The [[https://www.wikidata.org/wiki/Q359442][Bernie Sanders]] has listings
  under [[https://www.wikidata.org/wiki/Q359442#Q359442$2E8E9668-A248-447D-A12D-EC8B8C34DF5C][position held]]).  The latest upload lists =position held= as [[https://www.wikidata.org/wiki/Q4416090][United States senator]] and lists a
  [[https://www.wikidata.org/wiki/Property:P2937][parliamentary term]].  Older style entries were not as comprehensive and are either missing
  parliamentary term or list =position held= with the more specific form [[https://www.wikidata.org/wiki/Q980774cl91][United States senator (116th
  Congress)]].  The goal is to consolidate all of these entries into a single form and ideally
  automate a process for keeping this information up-to-date.

*** Wikidata SPARQL queries
  You can search through Wikidata using a [[https://query.wikidata.org/][SPARQL query]].

  - Here are all the =position held= statements for Bernie Sanders:
    #+begin_src sql
    SELECT ?statement ?val ?unitLabel WHERE {
      wd:Q359442 p:P39 ?statement.
      ?statement ps:P39/wd:Q21514624* wd:Q4416090.
    }
    #+end_src
  - Here are all the statements that need deleting.  Specifically those which use =United States
    senator (116th Congress)=

    #+begin_src sql
    SELECT ?sen ?senLabel ?positionLabel ?statement WHERE {
      ?sen p:P39 ?statement.
      ?statement (ps:P39/(wdt:P279+)) wd:Q4416090;
        (ps:P39/p:P31/pq:P4649/wdt:P31) wd:Q15238777;
        ps:P39 ?position.
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
    }
    #+end_src

  - Here are all the =position held= =United States senator= items without a =legislative term=.
    #+begin_src sql
    SELECT ?sen ?senLabel ?statement WHERE {
      ?sen wdt:P39 wd:Q4416090;
        p:P39 ?statement.
      ?statement ps:P39 wd:Q4416090.
      FILTER(NOT EXISTS { ?statement pq:P2937 ?term. })
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
    }
    #+end_src
  - Here are all the =position held= =United States senator= items which have duplicates.
    #+begin_src sql
    SELECT * WHERE {
    {SELECT ?sen ?senLabel ?termLabel (COUNT( ?statement) as ?cnt ) WHERE {
      ?sen wdt:P39 wd:Q4416090;
        p:P39 ?statement.
      ?statement ps:P39 wd:Q4416090;
       pq:P2937 ?term.
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
    } group by ?sen ?term ?senLabel ?termLabel }
    FILTER ( ?cnt > 1 )
    }
    #+end_src
  - Here are all the senators after [[https://www.senate.gov/artandhistory/history/common/briefing/Direct_Election_Senators.htm][1913]], which have overlapping periods in office and so need fixing.
    #+begin_src sql
    SELECT * WHERE {
      {
        SELECT DISTINCT (COUNT(?stmt) AS ?cnt) ?district ?start WHERE {
          ?sen p:P39 ?stmt;
            wdt:P31 wd:Q5.
          ?stmt ps:P39 wd:Q4416090;
            pq:P2937 ?term;
            pq:P580 ?start;
            pq:P768 ?district.
          SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
        }
        GROUP BY ?district ?start
      }
      FILTER( ?cnt > 1 )
      FILTER(?start > "1913-01-01T00:00:00Z"^^xsd:dateTime)
      ?sen2 p:P39 ?stmt2;
        wdt:P31 wd:Q5.
      ?stmt2 ps:P39 wd:Q4416090;
        pq:P2937 ?term;
        pq:P580 ?start;
        pq:P768 ?district.
    }
    ORDER BY (?district) (?start)
    #+end_src
  - Generates list of "runs" in the senate.  One line for starts and another for ends.
    #+begin_src sql
    SELECT ?sen ?senLabel ?seatLabel ?replaces ?replacedBy ?start ?end ?termLabel WHERE {
      ?sen p:P39 ?stmt.
      ?stmt ps:P39 wd:Q4416090;
        pq:P2937 ?term;
            pq:P768 ?seat.
      OPTIONAL
      {
        ?stmt pq:P1365 ?replaces;
          pq:P580 ?start.
      }
      OPTIONAL
      {
        ?stmt pq:P1366 ?replacedBy;
          pq:P582 ?end.
      }
      BIND(COALESCE(?start, ?end) AS ?date)
      FILTER( BOUND(?date) )
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
    }
    ORDER BY (?seatLabel) (?date)
    #+end_src
  - Representatives without term and district
    #+begin_src sql
    SELECT DISTINCT ?item ?bioid ?start ?end ?replacedBy ?replaces ?group ?location ?elected ?endCause ?ps WHERE { 
    #SELECT DISTINCT ?pred WHERE {
      ?item p:P39 ?ps; wdt:P31 wd:Q5; wdt:P1157 ?bioid .
      ?ps ps:P39 wd:Q13218630.

      OPTIONAL { ?ps pq:P580 ?start }
      OPTIONAL { ?ps pq:P582 ?end }
      OPTIONAL { ?ps pq:P1366 ?replacedBy }
      OPTIONAL { ?ps pq:P1365 ?replaces }
      OPTIONAL { ?ps pq:P4100 ?group }
      OPTIONAL { ?ps pq:P276 ?location }
      OPTIONAL { ?ps pq:P2715 ?elected }
      OPTIONAL { ?ps pq:P1534 ?endCause }


      FILTER NOT EXISTS { ?ps pq:P2937 ?term }
      FILTER NOT EXISTS { ?ps pq:P768 ?district }
      FILTER NOT EXISTS { ?item p:P39 [ ps:P39 wd:Q13218630; pq:P768 []; pq:P2937 [] ] }
      #?ps ?pred [].
    }
    #+end_src

*** DONE Figure out what's missing from old upload to full upload.
    SCHEDULED: <2020-11-01 Sun>
    :PROPERTIES:
    :ID:       C0A20768-0E84-4E14-B5CE-061DC1F15215
    :END:
  !
*** TODO Change [[https://www.wikidata.org/wiki/Property:P768][electoral district]] to reflect the class of the senate seat.
  This was [[https://www.wikidata.org/wiki/Wikidata:Project_chat#Representing_United_States_Senate_classes][discussed]] on Wikidata's project chat.  I've generated [[https://www.wikidata.org/wiki/Help:QuickStatements][QuickStatements]] to create the [[file:~/Anki/Anki-dm/wikidata/state-classes.qs][new
  items]].  This was pretty straightforward in [[https://openrefine.org/documentation.html][OpenRefine]] using the [[https://github.com/gitonthescene/wikidata/blob/master/every_politician/United_States_of_America/Senate/stateclasses.tsv][table of state classes]].

*** DONE Add references to [[https://www.wikidata.org/wiki/Property:P1157][US Congress Bio ID]] as in [[https://www.wikidata.org/wiki/Q5235859#Q5235859$6D31F8C0-F6C1-4289-A5AF-2001BBC64161][this statement]].

*** Add appropriate end cause for the oddball cases.
  These senators are the oddball cases.  Either never seated or disqualified.
    #+begin_src
    wd:Q500046	Albert Gallatin
    wd:Q327388	Michael Hahn
    wd:Q4803331	Asahel C. Beckwith
    wd:Q6222555	William Scott Vare
    #+end_src

  Should put in an appropriate end cause.  This lists them all:
    #+begin_src sql
    SELECT DISTINCT ?cause ?causeLabel WHERE {
      ?subj pq:P1534 ?cause;
            ps:P39 ?obj.
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
    }
    #+end_src

  - For Gallatin, perhaps ~wd:Q1229261 disqualification~?
  - For all appointed Senators who were not re-elected maybe ~wd:Q22087114 not re-elected~??
    #+begin_src sql
    SELECT * WHERE {
      VALUES ?bioid {
        "W000059" "W000114" "N000142" "T000086" "J000220" "G000489" "B001051" "W000324" "P000322" "E000136"
        "H000226" "R000378" "B000058" "F000304" "M000889" "B000168" "W000646" "S000905" "F000174" "M000596"
        "M000650" "R000368" "C000656" "F000174" "W000138" "B000960" "F000106" "S000809" "W000609" "J000103"
        "W000629" "C000952" "E000185" "P000530" "A000279" "B000331" "P000557" "E000046" "H000428" "C000343"
        "M000165" "C000357" "J000063" "P000141" "T000324" "R000450" "G000112" "B000386" "S000917" "E000109"
        "P000570" "H000457" "S000038" "M000229" "J000196" "Y000046" "P000238" "J000030" "W000305" "D000495"
        "G000522" "B000360" "W000471" "C000657" "R000075" "F000069" "A000028" "B001196" "W000499" "C001028"
        "G000510" "B000053" "A000126" "M000392" "S001060" "M000993" "W000069" "P000091" "C000597" "E000202"
        "T000225" "L000400" "B000389" "H000612" "H000646" "R000099" "M000787" "B000417" "S000478" "B001061"
        "B000099" "R000443" "W000096" "J000026" "W000248" "H000913" "S001117" "S000792" "B001069" "D000522"
        "L000173" "D000048" "P000575" "S000517" "B000966" "M000236" "F000438" "C001099"
      }
      ?sen p:P39 ?ps;
        wdt:P1157 ?bioid.
      ?ps ps:P39 wd:Q4416090;
        pq:P2937 ?term;
        pq:P582 ?end;
        pq:P580 ?start.
      ?term wdt:P580 ?termStart;
        wdt:P582 ?termEnd;
        (p:P31/pq:P1545) ?termNum.

      BIND(URI(CONCAT("https://bioguideretro.congress.gov/Home/MemberDetails?memIndex=", ?bioid)) AS ?bioURL)
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
    }
    ORDER BY (xsd:integer(?termNum))
    #+end_src
  - I think there are cases of ~wd:Q25235916 election result invalidated~.

*** Collect district info from [[https://github.com/JeffreyBLewis/congressional-district-boundaries.git][congressional district maps]]
   This github site has geojson files with the shapes of all the historical congressional
   districts.  In addition they've collected info about which representatives served in those
   districts for which terms.  This should be a nice supplement to the info available from the
   [[https://bioguideretro.congress.gov/][Biographical Directory]].  Extracting from json is easier using [[https://stedolan.github.io/jq/manual/][jq]].

   I used the following pipeline:
   #+begin_src sh
   $ cat *.geojson | jq -r '.features[].properties | \
                            { statename: .statename, member: [ .member | to_entries ][0][]  } | \
                            { state: .statename, congress: .member.key, member: [.member.value| to_entries][0][].value } | \
                            { state: .state, congress: .congress, party: .member.party, name: .member.name, district: .member.district } '
   #+end_src

**** Note that for two files the format of the congressional information is different.
     The files ~South_Carolina_104_to_107.geojson~ and ~South_Carolina_108_to_112.geojson~ have
     member information formatted slightly differently.  I should get in touch with the author to
     point that out.  In fact, no time like the present.  I've [[https://github.com/JeffreyBLewis/congressional-district-boundaries/issues/6][opened an issue]].

*** Just discovered a git repository covering similar ground.
   [[https://github.com/unitedstates/congress-legislators][congress-legislators]]


*** No Wiki entry for [[https://www.nytimes.com/1990/08/23/obituaries/george-chambers-87-lost-disputed-election.html][George O. Chambers!]]

* Useful links
  - [[https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf][emacs reference card]]
